name: Generate phpDoc

# Allow GITHUB_TOKEN to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch: # Allow to manually deploy
  push:
    branches: ["phpdocs"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          path: source

      # Install phpDocumentator using PHIVE
      # phpDocumentor recommends PHIVE as the preferred install strategy
      # Source: https://github.com/phpDocumentor/phpDocumentor/blob/919d5c1ef42a3c74d050e05ce99add6efa87b5a4/README.md?plain=1#L79
      - name: Cache PHIVE tools
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.phive
          key: php-phive-${{ hashFiles('.phive/phars.xml') }}
          restore-keys: php-phive-

      # from https://github.com/phpDocumentor/phpDocumentor/pull/3695#discussion_r1559967797
      - name: "Build"
        uses: "phpDocumentor/phpDocumentor@master"
        with:
          target: "build/docs"

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
